name: Coding Standards and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2

      - name: Composer cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles( 'composer.lock' ) }}-${{ hashFiles( '.github/workflows/tests.yml' ) }}

      - name: Node cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-${{ hashFiles( 'package-lock.json' ) }}-${{ hashFiles( '.github/workflows/tests.yml' ) }}

      - name: Install Composer dependencies
        run: composer install --no-interaction

      - name: Install Node dependencies
        run: npm ci

      - name: Lint JS
        run: npm run lint:js

      - name: Lint CSS
        run: npm run lint:css

      - name: Lint PHP
        run: npm run lint:php

      - name: Format PHP
        run: npm run format:php

      - name: PHPStan
        run: npm run static-analysis:php

      - name: Start wp-env
        run: npm run wp-env:start

      - name: Run PHPUnit
        run: npm run test:php:setup

      - name: Stop wp-env
        if: always()
        run: npm run wp-env:stop
